image: python:3.6.6

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
    paths:
        - .cache/pip
        - venv/

before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

test:
    script:
        - python -m pytest tests/

quality:
    script:
        - pylint zoo
